# Generated by Django 3.2 on 2023-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('call_us', models.CharField(max_length=20)),
                ('email_us', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='company/')),
                ('subtitle', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=50)),
                ('mobile_numbers', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('app_description', models.TextField(blank=True, max_length=200, null=True)),
                ('app_play_store', models.URLField(blank=True, null=True)),
                ('app_app_store', models.URLField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
